output = "internal/repository/orm"
pkgname = "orm"
wipe = true
no-tests = false
add-enum-types = true
add-global-variants = false

[psql]
dbname = "warehouse"
host = "localhost"
port = "5432"
user = "postgres"
pass = "postgres"
sslmode = "disable"
schema = "public"
blacklist = ["schema_migrations"]
