// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	InvoiceProduct string
	Invoices       string
	Products       string
	Roles          string
	Users          string
}{
	InvoiceProduct: "invoice_product",
	Invoices:       "invoices",
	Products:       "products",
	Roles:          "roles",
	Users:          "users",
}
