package errors

const (
	ERR_INTERNAL_SERVER_ERROR             = "ERR_INTERNAL_SERVER_ERROR"
	ERR_INVALID_PARAMETER                 = "ERR_INVALID_PARAMETER"
	ERR_NOT_FOUND                         = "ERR_NOT_FOUND"
	ERR_OFFSET_AND_LIMIT_MUST_BE_POSITIVE = "ERR_OFFSET_AND_LIMIT_MUST_BE_POSITIVE"
	ERR_ID_MUST_BE_EMPTY                  = "ERR_ID_MUST_BE_EMPTY"
	ERR_ID_MUST_MATCH                     = "ERR_ID_MUST_MATCH"
)
