package errors

const (
	ERR_INTERNAL_SERVER_ERROR             = "ERR_INTERNAL_SERVER_ERROR"
	ERR_INVALID_PARAMETER                 = "ERR_INVALID_PARAMETER"
	ERR_NOT_FOUND                         = "ERR_NOT_FOUND"
	ERR_NO_DATA                           = "ERR_NO_DATA"
	ERR_OFFSET_AND_LIMIT_MUST_BE_POSITIVE = "ERR_OFFSET_AND_LIMIT_MUST_BE_POSITIVE"
	ERR_ID_MUST_BE_EMPTY                  = "ERR_ID_MUST_BE_EMPTY"
	ERR_ID_MUST_BE_MATCH                  = "ERR_ID_MUST_BE_MATCH"
	ERR_ID_MUST_BE_SET                    = "ERR_ID_MUST_BE_SET"
	ERR_BAD_REQUEST                       = "ERR_BAD_REQUEST"
	ERR_RELATION_DOES_NOT_EXIST           = "ERR_RELATION_DOES_NOT_EXIST"
	ERR_RELATION_EXISTS                   = "ERR_RELATION_EXISTS"
)
