// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("InvoiceProducts", testInvoiceProductsUpsert)

	t.Run("Invoices", testInvoicesUpsert)

	t.Run("Products", testProductsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("Users", testUsersUpsert)
}
